### PR TITLE
Changing landing page content and messaging

### PR DESCRIPTION
**Pull request by emilylaiken**
This request contains three small changes to the landing page:
 - The content is updated with text written by the communications team
 - The messaging in the nav bar buttons has been changed (specifically, the login/sign up buttons are collapsed into one and the call-out button now says "get in contact with us"--consistent with our mission of bringing more clients in to work one-on-one with the InSTEDD team)
 - As we have on other tool pages, we added a "contact-us" pop-up widget to encourage getting in touch with the team. This has proved our most effective method of converting website visitors into clients in the past year.

### CODE REVIEW

**Comment by emaraschio** [comment]
Thanks @emilylaiken, we will back to you ASAP.

**Comment by emilylaiken** [comment]
Hi Martin! Both these edits sounds good to me--thank you!

**Comment by mverzilli** [comment]
Great, Emily! Would you mind adding a new commit with those edits to this PR then we'll merge. Thanks!

**Comment by mverzilli** [comment]
Thank you Emily!

**Pull request merged**
